### ISSUE TITLE
Gym reset method seed argument mismatch - find_and_avoid_v2

### ISSUE THREAD

**Issue by wayne-weiwei** [aidudezzz/deepworlds#105]
Hello,

I am currently working with stable-baselines3 (version 1.8.0) and the sb3-contrib PPO Mask algorithm for my custom environment, FindAndAvoidV2RobotSupervisor. While running the code, I encountered the following error:
```
2024-09-25 16:47:42.799676: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/anaconda3/envs/omnisafe/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:77: UserWarning: The `render_mode` attribute is not defined in your environment. It will be set to None.
  warnings.warn("The `render_mode` attribute is not defined in your environment. It will be set to None.")
Traceback (most recent call last):
  File "/home/webots/projects/deepworlds-dev/examples/find_and_avoid_v2/controllers/robot_supervisor_manager/robot_supervisor_manager.py", line 95, in <module>
    env = PPO_trainer.run(experiment_name=experiment_name, experiment_description=experiment_description,
  File "/home//webots/projects/deepworlds-dev/examples/find_and_avoid_v2/controllers/robot_supervisor_manager/PPO_trainer.py", line 230, in run
    model.learn(total_timesteps=difficulty_dict[diff_key]["total_timesteps"], tb_log_name=diff_key,
  File "/home/anaconda3/envs/omnisafe/lib/python3.10/site-packages/sb3_contrib/ppo_mask/ppo_mask.py", line 441, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home/anaconda3/envs/omnisafe/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "/home/anaconda3/envs/omnisafe/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 77, in reset
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset(seed=self._seeds[env_idx], **maybe_options)
  File "/home/anaconda3/envs/omnisafe/lib/python3.10/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/anaconda3/envs/omnisafe/lib/python3.10/site-packages/gymnasium/core.py", line 414, in reset
    return self.env.reset(seed=seed, options=options)
TypeError: FindAndAvoidV2RobotSupervisor.reset() got an unexpected keyword argument 'seed'
Using cuda device
Wrapping the env in a DummyVecEnv.
Changed difficulty to: {'type': 'random', 'number_of_obstacles': 10, 'min_target_dist': 10, 'max_target_dist': 10, 'total_timesteps': 262144}
WARNING: 'robot_supervisor_manager' controller exited with status: 1.
```
Additional Information:
Environment:
Python 3.10
gym version: 0.21.0
gymnasium version: 0.28.1
stable-baselines3 version: 1.8.0
sb3-contrib version: Latest

My question:
Should I adapt this environment to handle seed and options in the reset() method?
Is there a way to ensure backward compatibility with gym (0.21.0) and avoid gymnasium's API changes without modifying my environment?
Are there any recommended steps or alternative approaches to resolve this issue?
Any guidance on resolving this would be greatly appreciated!

**Comment by tsampazk** [comment]
Hey @wayne-weiwei, sorry for the late reply. Since you closed the issue, did you find a solution? Care to post it if so?

**Comment by wayne-weiwei** [comment]
Thank you so much for your reply. Due to a mismatch in the argument signature between the **gym environment's reset** method and the **custom reset** method defined in `FindAndAvoidV2RobotSupervisor`. Specifically, the gym environment's reset method expects the arguments seed and options, so we modified the reset function like 
`def reset(self, seed=None, options=None):
....`
